apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  description: A simple service example to showcase Backstage integration
  tags:
    - example
    - service
  annotations:
    github.com/project-slug: backstage/example-service
spec:
  type: service
  owner: user:default/guest
  lifecycle: production
